### ISSUE TITLE
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by adgad2** [Jai-wei/Gw2AutoPvp#7]
```
[INFO]~[19:24:01] 随机端口号16432
启动服务...
尝试本地启动 WindowsDriver ...
本地启动 WindowsDriver 成功，开始执行脚本
[INFO]~[19:24:03]  <329394> 开始第 <1> 场游戏
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 63619)
Traceback (most recent call last):
  File "F:\game\gw2\GW2AUT~1\socketserver.py", line 683, in process_request_thread
  File "F:\game\gw2\GW2AUT~1\socketserver.py", line 360, in finish_request
  File "F:\game\gw2\GW2AUT~1\AiBot\_WinBot.py", line 48, in __init__
  File "F:\game\gw2\GW2AUT~1\socketserver.py", line 747, in __init__
  File "F:\game\gw2\GW2AUT~1\AiBot\_WinBot.py", line 960, in handle
  File "F:\game\gw2\GW2AUT~1\utils\FindImgs.py", line 53, in script_main
  File "F:\game\gw2\GW2AUT~1\AiBot\_WinBot.py", line 415, in find_images
  File "F:\game\gw2\GW2AUT~1\AiBot\_WinBot.py", line 71, in __send_data
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
----------------------------------------
```

使用一段时间后会出现这个

**Comment by adgad2** [comment]
不是百分百复现，已用管理员模式运行

**Comment by adgad2** [comment]
好像是因为我不小心把游戏最小化了导致的.....
